### ISSUE TITLE
Database creation failure

### ISSUE THREAD

**Issue by q1085909155** [Nolo001-Aha/SourceMod-ReBanner#1]
![image](https://user-images.githubusercontent.com/69096633/232309254-58fa065b-3e46-4b5e-8615-89c376faf0b7.png)

**Comment by Nolo001-Aha** [comment]
Hello!
Could you please show me the database config entry that's in addons/sourcemod/configs/databases.cfg?

This system only works with SQLite, which should nonetheless ship with SourceMod by default.

**Comment by q1085909155** [comment]
yeah, I know, I started using SQLite when I had an error. I thought you would support MySQL

**Comment by q1085909155** [comment]
I want to know, this plug-in will really have action, after my test, I will "fingerprint" after modification, re-enter the server, the server did not kick me out

**Comment by Nolo001-Aha** [comment]
Yea, my fault for not clearly stating it in the description.
Reason behind no MySQL is simple - SQLite implies a local database, and in my opinion, a database that stores all alt account SteamIDs and IP addresses should probably stay local only for security reasons.

**Comment by Nolo001-Aha** [comment]
Regarding Anti-tamper not kicking you (I assume that's what you meant):
Anti-tamper only checks the fingerprint if the plugin is unable to identify you via your SteamID and IP address.
In order to test the anti-tamper mode, you need to join with an alt account and change your IP address.

**Comment by q1085909155** [comment]
If you don't use MySQL, the fingerprint won't help much on multiple servers, and cheaters can use alternate accounts to play on another server

**Comment by q1085909155** [comment]
Ok, I see, fingerprints as a last line of defense

**Comment by Nolo001-Aha** [comment]
Yea, I don't see much of a reason to check existing local fingerprint file if I can already recognize players by SteamID and IP - only if both fail, then Ill query the fingerprint and try to use that for identification

**Comment by Nolo001-Aha** [comment]
Regarding MySQL - yeah, I also had thoughts about adding support for MySQL to make it work on multiple servers. 
Guess now that literally the first request is to add that, Ill have to implement it asap.

Do you have any other questions or can I close the issue?

**Comment by q1085909155** [comment]
yeah, it's my fault. I just wanted to test what would happen if I changed the fingerprint. hh, not necessarily. I still strongly recommend using MySQL, since most server operators run multiple servers.

**Comment by q1085909155** [comment]
oh, I have no more questions. If I have more questions, I will keep asking you

**Comment by Nolo001-Aha** [comment]
Sure thing, Ill add MySQL support then.

**Comment by Nolo001-Aha** [comment]
@q1085909155 Hello once again, experimental support for MySQL is in the new branch:
https://github.com/Nolo001-Aha/SourceMod-ReBanner/tree/mysql-support-test

Can't really create a test MySQL db atm, but theoretically that's all there is to it, rest of the transactions use identical syntax for both engines.

To use it, please download the mysql-support-test branch, comment out #define SQLITE at the top of rebanner.sp and compile the plugin. Ofc don't forget to change the databases.cfg file accordingly.

**Comment by Nolo001-Aha** [comment]
Edit:
No need for defines at compile time.
Just re-compile the plugin from mysql-support-test branch and edit your databases.cfg file to use mysql.
The plugin should detect driver type at runtime and use proper syntax.

**Comment by q1085909155** [comment]
Thank you
