### ISSUE TITLE
Not downloading files from FastDL | FastDownloads Method on TF2 not work and broke download

### ISSUE THREAD

**Issue by WOLFA22** [Nolo001-Aha/SourceMod-ReBanner#16]
# rebanner.cfg:

```
"settings"
{
	"fingerprint path"			"sound/votes/vote_second.wav"
	"ban reason"				"Connection Prohibited"
	"tampering kick reason"		"The integrity of the downloaded files is broken."
	"enable"					"1"
}
```

# Serve.php 
```$fingerpintFilePath = "sound/votes/vote_second.wav";```

# Game Debug: 
![debug_download](https://user-images.githubusercontent.com/35665773/235432582-b2f53034-d2c8-4658-bca0-66766a4cacd8.png)

What do I need to do, or where did I go wrong with the installation?

Windows 10 x64 Pro. All modules updated.

**Comment by naydef** [comment]
Hello. This issue (serve.php not adding Content-Length header field, which seems to be the issue here) was fixed recently. Please get the latest version of the plugin from the Github repo.

**Comment by WOLFA22** [comment]
Thank you for the warning. It's all working.
