### ISSUE TITLE
Problem with serve.php

### ISSUE THREAD

**Issue by FFFAS444** [Nolo001-Aha/SourceMod-ReBanner#26]
When I go to the file it's saying "No webpage was found for the web address" but file is there I don't know why

**Comment by naydef** [comment]
Uh, I guess you didn't put it in the right place (the file). Not sure about that, give more info maybe?

**Comment by FFFAS444** [comment]
I put it in the Fastdl folder that and when I go to that file it shows that error

**Comment by FFFAS444** [comment]
Ok I figured it out.

**Comment by FFFAS444** [comment]
ok when I join the server with the plugin loaded it crashes the server and there's no error about the plugin

**Comment by naydef** [comment]
Are you sure it's the plugin doing that?
Also post accelerator crash link.

**Comment by FFFAS444** [comment]
https://crash.limetech.org/sqg5wfvsuz6f

**Comment by naydef** [comment]
You forgot to mention what game.

**Comment by FFFAS444** [comment]
It's TF2

**Comment by FFFAS444** [comment]
Hello? Are you guys working on fixing the issue I have?

**Comment by naydef** [comment]
Hello. Update your gamedata file using the one from the repo and report whether this fixed the crashes.

**Comment by FFFAS444** [comment]
ok it fixes the crashes but now I'm getting this error 
L 07/23/2023 - 15:00:07: [SM] Exception reported: Could not find fingerprint file on disk! Should never happen?
L 07/23/2023 - 15:00:07: [SM] Blaming: rebanner.smx
L 07/23/2023 - 15:00:07: [SM] Call stack trace:
L 07/23/2023 - 15:00:07: [SM]   [0] SetFailState
L 07/23/2023 - 15:00:07: [SM]   [1] Line 645, rebanner.sp::RequestClientFingerprint
L 07/23/2023 - 15:00:07: [SM]   [3] Call_Finish
L 07/23/2023 - 15:00:07: [SM]   [4] Line 405, filenetwork.sp::CallRequestFileFinish
L 07/23/2023 - 15:00:07: [SM]   [5] Line 298, filenetwork.sp::OnFileReceived

and when I try to change the map it says Download file '/PATH' already exists!

**Comment by naydef** [comment]
Try using this filenetwork gameata: https://github.com/Nolo001-Aha/File-Network/blob/502a482bd0f9785a0e7be86e00b54632f797649d/gamedata/filenetwork.txt

Hopefully Nolo merges the changes soon. Report once you test.

**Comment by FFFAS444** [comment]
The file network is not downloading the file from the FastDL server and when a banned player joins with a different IP they still have access to join.
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12142011/rebanner.log)

**Comment by FFFAS444** [comment]
The player fingerprints are not added to the database tables and when a banned player joins from different IPs they still have access to join.
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12143933/rebanner.log)

**Comment by FFFAS444** [comment]
please reply if you guys are working on it

**Comment by naydef** [comment]
Sadly I'm not very knowledgeable in the inner working of this plugin, nor I have suitable environment to make testing.
I'll see what can be done about this issue.

**Comment by naydef** [comment]
Please check this version and report: https://github.com/naydef/SourceMod-ReBanner/blob/main/sourcemod/scripting/rebanner.sp

**Comment by FFFAS444** [comment]
It's not receiving the fingerprint when I try to connect to the server.
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12176055/rebanner.log)

**Comment by naydef** [comment]
It seems I made a number of mistakes when I updated the gamedata of [FileNetwork](https://github.com/Nolo001-Aha/File-Network). Please update your gamedata again and retest.

**Comment by FFFAS444** [comment]
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12176883/rebanner.log)

**Comment by naydef** [comment]
the `RIFF` text points out that the client downloads the .wav sound instead of the ID, did you set `fingerpintFilePath` properly in the serve.php script?

Also make sure to delete the local file which you already downloaded so that fresh fingerprint file is acquired.

**Comment by FFFAS444** [comment]
Alright, I fixed the fingerprint path in serve.php but this error still occurs 
[errors_20230726.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12177288/errors_20230726.log)

**Comment by naydef** [comment]
I'm a bit clueless here, but try this: https://github.com/naydef/SourceMod-ReBanner/blob/main/sourcemod/scripting/rebanner.sp

**Comment by FFFAS444** [comment]
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12182647/rebanner.log)

**Comment by naydef** [comment]
uhm, ok. Any errors? This does look like the previous issue where no file receive callback is being sent...

**Comment by FFFAS444** [comment]
no there's no error

**Comment by FFFAS444** [comment]
any update?

**Comment by naydef** [comment]
Right now no idea why it fails...

**Comment by naydef** [comment]
Did you do the logging with `rb_log_level = 3`?

**Comment by FFFAS444** [comment]
yes

**Comment by FFFAS444** [comment]
oh I'm getting this error again
[errors_20230730.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12208750/errors_20230730.log)

**Comment by FFFAS444** [comment]
![rebanner](https://github.com/Nolo001-Aha/SourceMod-ReBanner/assets/81820237/681d3995-535f-47bf-9b06-11b7a2c12d56)
I deleted the file that I highlighted from my computer it redownloads but the console says it already exists and rebanner doesn't receive the player fingerprint

**Comment by naydef** [comment]
Thanks. That's a useful clue to what exactly fails. Please test latest version.

**Comment by FFFAS444** [comment]
It still occurs and when I change the map this file network error shows up again
[errors_20230730.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12209099/errors_20230730.log)
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12209100/rebanner.log)

**Comment by naydef** [comment]
Any message in console when player connecting?

**Comment by FFFAS444** [comment]
![Capture](https://github.com/Nolo001-Aha/SourceMod-ReBanner/assets/81820237/8d0804b0-ff2f-453a-ab3e-71ede041fc2c)

**Comment by naydef** [comment]
Uh, does the file `download/materials/free_duel/BLU_Target.vmt `exist in your server? It's supposed to get deleted on plugin load, but I'm not sure why it still exists. 

Try to manually delete this file and check whether it reappers.

**Comment by FFFAS444** [comment]
ok I deleted /materials/free_duel/BLU_Target.vmt from my server and this error appears
[errors_20230730.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12209630/errors_20230730.log)

**Comment by naydef** [comment]
So yea, do as the message says, basically create this file (or at least build the folder structure of the file), make sure to create it NOT INSIDE `download` folder, but outside of it.

**Comment by FFFAS444** [comment]
Alright I think I fixed it 
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12209659/rebanner.log)

**Comment by naydef** [comment]
Did the file `download/materials/free_duel/BLU_Target.vmt`  reappear? Maybe It reappeared and now it's again showing the message that this file exists in console.

**Comment by FFFAS444** [comment]
I created the new materials folder called materials2 and that already exist error gone

**Comment by naydef** [comment]
Hm, then I suppose issue is solved, maybe?

**Comment by FFFAS444** [comment]
when I try to reconnect the server this shows up again 
[errors_20230730.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12209716/errors_20230730.log)

**Comment by naydef** [comment]
Yea ... I have no idea...

**Comment by FFFAS444** [comment]
yeah when it received the fingerprint at the first join but then after you rejoin the server the plugin shows the error that I've posted above

**Comment by naydef** [comment]
Sadly I think there's some oddity with your TF2 server, I'm unable to completely understand why it sometimes things fail.

When this error shows, does file `download/materials/free_duel/BLU_Target.vmt` exist?

**Comment by FFFAS444** [comment]
I deleted the download folder from the server but after I joined the download folder kept recreating with the path to the VMT file inside it

**Comment by naydef** [comment]
Hello again. Please test this version: https://github.com/Nolo001-Aha/SourceMod-ReBanner/blob/naydef-patch-1/sourcemod/scripting/rebanner.sp

**Comment by FFFAS444** [comment]
![rebanners](https://github.com/Nolo001-Aha/SourceMod-ReBanner/assets/81820237/c5a54448-5b5a-428c-ba46-a7f7035d37a5)
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12217976/rebanner.log)

I can't use the path that I've used before now I have to use the full path to the .VMT file

**Comment by naydef** [comment]
Hm, yea, i made some changes.

**Comment by FFFAS444** [comment]
[rebanner.txt](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12220464/rebanner.txt)

**Comment by naydef** [comment]
Hm, yea... That doesn't look right. 

The fingerprint path is relative to the folder where the server is (in your case relative to `/home/tf2server/serverfiles/tf/`), not an absolute path. So I believe the correct `fingerprint path` is `materials/free_duel/BLU_Target.vmt`

**Comment by FFFAS444** [comment]
After I changed to that path it shows this error 
[rebanner.txt](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12221556/rebanner.txt)
![Capture](https://github.com/Nolo001-Aha/SourceMod-ReBanner/assets/81820237/b4031a6d-603c-4b7a-a2c9-c014e0102960)

**Comment by naydef** [comment]
As I mentioned before, build the directory structure to the file (it's not necessary to create it, however). Most probably you should create the directory structure inside `download` folder or in the base server folder, in order to be sure create it in both places i guess.

**Comment by naydef** [comment]
Uh, pictures or log? Also did you name the file with wrong casing?

**Comment by FFFAS444** [comment]
no, I use BLU_Target.vmt and it was working before
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12221773/rebanner.log)

**Comment by naydef** [comment]
Try newest version. Alternatively maybe try to rename the file so that It has correct casing and try again. No idea...

**Comment by Skootie812** [comment]
Alright so after I join the server the plugin only received rebanner_ips and rebanner_steamids and after I rejoin again it's showing the duplicate entry error 

![Capture](https://github.com/Nolo001-Aha/SourceMod-ReBanner/assets/81820237/a14281fe-3270-4571-8440-bc547809399e)
and here is the log
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12222635/rebanner.log)

**Comment by naydef** [comment]
I'll investigate the rest of these issues, but the fingerprint file MUST NOT exist in the fastdl, same applies for the compressed bz2 file equivalent, too. Maybe after all just change the fingerprint file name to `blu_target2.vmt` and leave the plugin do the setup of the file automatically.

About the duplicate SQL error, that's completely different, but know issue. I'll see what I can do with it later.

**Comment by naydef** [comment]
I guess your `rebanner.cfg` config specifies the fingerprint file in the wrong case for some letters. The letter case must absolutely match the case of the path and the file. Show your `rebanner.cfg` again...

**Comment by Skootie812** [comment]
![Capture](https://github.com/Nolo001-Aha/SourceMod-ReBanner/assets/81820237/f25bb2cd-6942-4b88-8ed7-40a7f3629788)
[rebanner.txt](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12229497/rebanner.txt)

**Comment by naydef** [comment]
The fingerprint file must be a file which is not used by any model or in any other way...
If `blu_target.vmt` is not used by anything, delete this file both on server and in fastdl.

**Comment by Skootie812** [comment]
alright deleted both on server and in fastdl

**Comment by Skootie812** [comment]
How it's going?

**Comment by naydef** [comment]
Waiting for you to report.

**Comment by Skootie812** [comment]
[rebanner.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12249802/rebanner.log)
[errors_20230802.log](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/12249803/errors_20230802.log)

**Comment by Skootie812** [comment]
this is all I have at this moment
