### ISSUE TITLE
Plugin is not compiling...

### ISSUE THREAD

**Issue by MickaNoob** [Nolo001-Aha/SourceMod-ReBanner#4]
Hello, 

I have a litte problem with this plugins is not compiling, with the latest version

![image](https://user-images.githubusercontent.com/20491694/233467041-7398f0d2-ab3f-426a-9aa2-634c2a019846.png)

**Comment by naydef** [comment]
You'll want to use [Nolo's FileNetwork](https://github.com/Nolo001-Aha/File-Network/commit/6f3ac1c0f42db184a63c83696d9bf57eaaa2793f) plugin for now.
This plugin is still in active development...

**Comment by MickaNoob** [comment]
I'm talking about rebanner plugins not files Network, this plugin is working for me.

**Comment by naydef** [comment]
Well, I meant SourceMod-ReBanner is still in active development.
And I said you probably need Nolo's custom filenetwork plugin and include files, which Sourcemod Rebanner relies on.

**Comment by MickaNoob** [comment]
Fixed with the latest version :)
