### ISSUE TITLE
Error gamedata file

### ISSUE THREAD

**Issue by MickaNoob** [Nolo001-Aha/SourceMod-ReBanner#6]
Hi, 

I have this error with the latest version of gamedata file. 

`L 04/22/2023 - 11:18:17: [SM] Exception reported: Failed to load CBaseClient::SendServerInfo signature from gamedata!
L 04/22/2023 - 11:18:17: [SM] Blaming: rebanner.smx
L 04/22/2023 - 11:18:17: [SM] Call stack trace:
L 04/22/2023 - 11:18:17: [SM]   [0] SetFailState
L 04/22/2023 - 11:18:17: [SM]   [1] Line 204, Z:\0_SOURCEMOD COMPILER\rebanner.sp::OnPluginStart
L 04/22/2023 - 11:18:17: [SM] Unable to load plugin "rebanner.smx": Error detected in plugin startup (see error logs)`

I have used your latest version Rebanner 1.3 and the last version in repo but not working

**Comment by Nolo001-Aha** [comment]
Hi.

What's the game and what's the OS?

**Comment by MickaNoob** [comment]
CSGO and linux server

**Comment by Nolo001-Aha** [comment]
Please try the following Linux CSGO signature for CBaseClient::SendServerInfo:
\x55\x89\xE5\x57\x56\x53\x81\xEC\x2C\x09\x00\x00\x8B\x2A\x2A\x89

(Just replace the old value between two quotemarks and reload the plugin)

**Comment by MickaNoob** [comment]
Okay i going to try this

**Comment by MickaNoob** [comment]
Working

**Comment by Nolo001-Aha** [comment]
Thank you. Will push to master asap.
