### ISSUE TITLE
Question about error and database

### ISSUE THREAD

**Issue by MickaNoob** [Nolo001-Aha/SourceMod-ReBanner#7]
The plugins seems to be well configured, but I have a problem.
I can download the file correctly but my ID is not stored in the database, it remains empty. 
And I have an error in the logs. 
Did I do something wrong? 
```

L 04/22/2023 - 13:52:28: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 04/22/2023 - 13:52:28: [SM] Blaming: rebanner.smx
L 04/22/2023 - 13:52:28: [SM] Call stack trace:
L 04/22/2023 - 13:52:28: [SM]   [0] ConVar.SetInt
L 04/22/2023 - 13:52:28: [SM]   [1] Line 352, Z:\0_SOURCEMOD COMPILER\rebanner.sp::OnAllPluginsLoaded
```
![image](https://user-images.githubusercontent.com/20491694/233783323-c7bbec48-d37a-40d2-a4d5-206cf0aae255.png)
![image](https://user-images.githubusercontent.com/20491694/233783327-8ea3ffbb-b552-42ba-96e0-543240a6908a.png)
![image](https://user-images.githubusercontent.com/20491694/233783333-d2223a0e-e8ec-47d1-b334-607f09bcc728.png)
![image](https://user-images.githubusercontent.com/20491694/233783345-59b41910-1961-4578-9cfd-55a171628167.png)
![image](https://user-images.githubusercontent.com/20491694/233783380-3fe4d77a-e370-41ca-b8c1-69cb18234463.png)

**Comment by Nolo001-Aha** [comment]
Hello!

During early connection stages, Re-Banner does not add fingerprints to the database.
If it did, clients that changed SteamID and IP, but kept their original fingerprint clientside would get a new fingerprint record too, which is bad.


Re-Banner generates a new fingerprint when you connect from new accounts and IP address, then temporarily stores them in memory.
Then, when you fully join the server, Re-Banner queries your game files for the fingerprint file.

Source Engine FastDownloads are implemented in such a way that if you already have the file locally, you will not re-download it (even if they're different files). This lets Re-Banner safely send new fingerprints to clients it cannot recognize by Steam and IP. Best case scenario - the file won't get overwritten, and the plugin will be able to query the actual clientside value. Worst case the client did in fact not have the file before connecting, and so the newly generated value will be received.

Only after Re-Banner queries the local file, will it add anything to the database.

**Comment by Nolo001-Aha** [comment]
Regarding the error log:

This is extremely unusual, almost as if like cl_allowupload doesn't exist serverside for CSGO, so wth?

I guess you could remove 

        FindConVar("cl_allowupload").SetInt(1);
        FindConVar("cl_allowdownload").SetInt(1);

from OnAllPluginsLoaded() and try to compile the plugin that way.

**Comment by MickaNoob** [comment]
Okay

**Comment by Nolo001-Aha** [comment]
Also, what is your value of sv_allowupload?
I see a double forward slash here:

![image](https://user-images.githubusercontent.com/56518932/233785176-2ba3d53d-51ef-42a4-a6fb-28d9c166b027.png)

It might be OK, cURL for Linux and built-in Windows APIs should be able to resolve that, but it's still suspicious.

**Comment by MickaNoob** [comment]
> sv_downloadurl "https://fastdl.absynthium.com/"

Yes, but the file downloads to the right place.

Simply CSGO does not like subdomains

**Comment by MickaNoob** [comment]
> Regarding the error log:
> 
> This is extremely unusual, almost as if like cl_allowupload doesn't exist serverside for CSGO, so wth?
> 
> I guess you could remove
> 
> ```
>     FindConVar("cl_allowupload").SetInt(1);
>     FindConVar("cl_allowdownload").SetInt(1);
> ```
> 
> from OnAllPluginsLoaded() and try to compile the plugin that way.

In CSGO , Cl_* --> Client config
sv_* --> Server config

**Comment by Nolo001-Aha** [comment]
As an alternative, you can remove public void OnAllPluginsLoaded() and it's ConVar manipulation from the src entirely, and instead set these cvars in your server.cfg file.

**Comment by MickaNoob** [comment]
![image](https://user-images.githubusercontent.com/20491694/233785643-69efb1c9-b9de-4d95-b9e5-b4703b3fdabd.png)

**Comment by Nolo001-Aha** [comment]
This is insane. Is this the latest build of Linux CS:GO?

If so, I'll remove this from the plugin entirely.

**Comment by MickaNoob** [comment]
Yeap, latestbuild of Linux CSGO

**Comment by Nolo001-Aha** [comment]
Please re-load the plugin and try re-joining the server, **delete your fingerprint file locally beforehand.**

It should send you a random new fingerprint value.
When you fully connect, it will query your local files and find out that your fingerprint is what it sent you during early connection, and that means that you did not have the file before connecting.
Only then will it add your fingerprint to the database.

**Comment by MickaNoob** [comment]
Okay i'm trying this

**Comment by MickaNoob** [comment]
File is correctly downloaded.

![image](https://user-images.githubusercontent.com/20491694/233786455-86146882-6346-4247-ba7f-6c8d90992e25.png)
I got my custom identity.

![20230422150159_1](https://user-images.githubusercontent.com/20491694/233786471-5585ecf6-67fb-424f-bf20-7c365d269093.jpg)

**Comment by MickaNoob** [comment]
Ok, when i retry the game, I got this error. 
```

L 04/22/2023 - 15:06:07: [SM] Exception reported: Client 2 is not connected
L 04/22/2023 - 15:06:07: [SM] Blaming: rebanner.smx
L 04/22/2023 - 15:06:07: [SM] Call stack trace:
L 04/22/2023 - 15:06:07: [SM]   [0] GetClientAuthId
L 04/22/2023 - 15:06:07: [SM]   [1] Line 266, Z:\0_SOURCEMOD COMPILER\rebanner.sp::buildConVarMessageDetCallback_Pre
```

**Comment by Nolo001-Aha** [comment]
This is... also unusual.

Can you please re-load the plugin and re-join the server to see whether the issue repeats?
I might've found the problem.

**Comment by MickaNoob** [comment]
After Reload plugins 
```
[DEBUG] Generating new fingerprint for client MickaNoob
[DEBUG] Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=74168694472393858495311009&url=
[DEBUG] Resetting to default FastDownload address.
[DEBUG] Processing queued client MickaNoob
[DEBUG] Requesting client fingerpint via File Network...
```

**Comment by Nolo001-Aha** [comment]
Local file is not supposed to change, as you already have it.

This looks like a File Network issue on Linux CS:GO. The project was only tested in Windows environments, so that's an oversight on my end.

Currently setting up a Linux CS:GO server locally to debug the issue.
Will post an update here asap, and sorry for the inconvenience.

**Comment by MickaNoob** [comment]
No problem, take the time you need, 
This plugin is really useful
When a project is in development, it's hard to have all the answers. Especially on a game as capricious as CSGO

**Comment by Nolo001-Aha** [comment]
I'm afraid that I cannot reproduce the issue of not receiving a file callback with a Linux CS:GO server and a Windows CS:GO client - in all cases it fires.

Are you using the latest version of File Network and it's gamedata (my fork)?
Please compile the latest one and try again.

Also, you may put PrintToConsoleAll(message) inside **void WriteToLog(const char message[], LogLevel level)**. That way it'll be easier to see debug in client consoles rather than a file.

**Comment by Nolo001-Aha** [comment]
[rebanner and filenet compiled, with gamedata.zip](https://github.com/Nolo001-Aha/SourceMod-ReBanner/files/11301550/rebanner.and.filenet.compiled.with.gamedata.zip)

I used these plugins and gamedata files to test.
For plugins, the only difference is printing some additional debug logs into server console.

**Comment by MickaNoob** [comment]
I'm trying this

**Comment by Nolo001-Aha** [comment]
There's an issue with client index offsets in Linux that I'm looking into right now (the invalid client index error you sent).
Still, reloading the plugin and re-joining should work at least once.

**Comment by MickaNoob** [comment]
After Reloading plugins

```
L 04/22/2023 - 16:55:58: [SM] Exception reported: Plugin handle 8400084 is invalid (error 1)
L 04/22/2023 - 16:55:58: [SM] Blaming: filenetwork.smx
L 04/22/2023 - 16:55:58: [SM] Call stack trace:
L 04/22/2023 - 16:55:58: [SM]   [0] Call_StartFunction
L 04/22/2023 - 16:55:58: [SM]   [1] Line 395, /home/nolo001/sourcemod/addons/sourcemod/scripting/filenetwork.sp::CallRequestFileFinish
L 04/22/2023 - 16:55:58: [SM]   [2] Line 270, /home/nolo001/sourcemod/addons/sourcemod/scripting/filenetwork.sp::OnClientDisconnect_Post
```

And this error again 

```
L 04/22/2023 - 16:54:32: [SM] Exception reported: Client 2 is not connected
L 04/22/2023 - 16:54:32: [SM] Blaming: rebanner.smx
L 04/22/2023 - 16:54:32: [SM] Call stack trace:
L 04/22/2023 - 16:54:32: [SM]   [0] GetClientAuthId
L 04/22/2023 - 16:54:32: [SM]   [1] Line 266, Z:\0_SOURCEMOD COMPILER\rebanner.sp::buildConVarMessageDetCallback_Pre
```

**Comment by Nolo001-Aha** [comment]
First error doesn't matter, it's expected.
2nd - looking into right now.

According to logs in server console and rebanner, did File Network get a callback after querying the fingerprint?

**Comment by MickaNoob** [comment]
```
[DEBUG] Generating new fingerprint for client MickaNoob
[DEBUG] Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=724550149951366880156761895&url=
[DEBUG] Resetting to default FastDownload address.
[DEBUG] Generating new fingerprint for client MickaNoob
[DEBUG] Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=295758183682380306152684801&url=
[DEBUG] Resetting to default FastDownload address.
```


724550149951366880156761895 First connexion no problems
get this  295758183682380306152684801 after reload rebanner

**Comment by MickaNoob** [comment]
Nothing else in the console about filenetwork

**Comment by Nolo001-Aha** [comment]
As I said, until the File Network query comes back (positive or negative, doesn't matter), the database will not get any data.

File Network queries seem to fail to respond, so rebanner just doesn't reach the database part.

In progress of debug, please wait.

**Comment by Nolo001-Aha** [comment]
@MickaNoob Hello!

Please download and compile the latest version of my File Network fork and Re-Banner from the master branches.

Tell me when you test it - it should work now, hopefully...

**Comment by MickaNoob** [comment]
> 

Hi, I'm trying this,

**Comment by MickaNoob** [comment]
It's strange, the plugins work correctly, however when I disconnect and reload the plugin, it wants to reassign me a new identity when I already have one. 

The file is well downloaded. At each reconnection it re-creates one.

```
[DEBUG] Generating new fingerprint for client MickaNoob
[DEBUG] Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=543535119718379843378852155&url=
[DEBUG] Resetting to default FastDownload address.
[DEBUG] Processing queued client MickaNoob, 1
[DEBUG] Requesting client fingerpint via File Network...
[DEBUG] Generating new fingerprint for client MickaNoob
[DEBUG] Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=295655300854061344620286901&url=
[DEBUG] Resetting to default FastDownload address.
[DEBUG] Processing queued client MickaNoob, 1
[DEBUG] Requesting client fingerpint via File Network...
[DEBUG] Generating new fingerprint for client MickaNoob
[DEBUG] Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=179594281283704457946735130&url=
[DEBUG] Resetting to default FastDownload address.
[DEBUG] Processing queued client MickaNoob, 1
[DEBUG] Requesting client fingerpint via File Network...
[DEBUG] Generating new fingerprint for client MickaNoob
[DEBUG] Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=785785158836367299515838916&url=
[DEBUG] Resetting to default FastDownload address.
[DEBUG] Processing queued client MickaNoob, 1
[DEBUG] Requesting client fingerpint via File Network...
```

Every ID = Retry game or reconnexion

**Comment by Nolo001-Aha** [comment]
Are these full logs, did you not cut out anything?

**Comment by Nolo001-Aha** [comment]
If these are full logs, then File Network is not working properly still... Which is unusual, I solved this bug in the latest commits, or at least the bug was solved locally.

Did you update both plugins and reload them properly?

**Comment by MickaNoob** [comment]
Yes, the logs are complete.
I shut down the server deleted the SMX files and restarted the server

**Comment by Nolo001-Aha** [comment]
Hmm...

When you fully connect to the server with Re-Banner stuck on requesting your file, you should see an error message in your client console, something like this:

![image](https://user-images.githubusercontent.com/56518932/233801332-efbda804-4865-405d-988d-660c979a4358.png)


Do you have it?

**Comment by MickaNoob** [comment]
Let me check

**Comment by MickaNoob** [comment]
Console log (First connexion) 
```

WARNING: BSP loaded VertexLitGeneric material: KA_SOCCER_2006/BALLON2
WARNING: BSP loaded VertexLitGeneric material: CS_HAVANA/METALFLUORESCENTSIDES01
SignalXWriteOpportunity(3)
ConVarRef stripper_current_file doesn't point to an existing ConVar
SetConVar: No such cvar ( stripper_current_file set to ba_jail_electric_razor_go), skipping
Error reading file materials/panorama/images/map_icons/screenshots/1080p/ba_jail_electric_razor_go.png.
Resource materials\panorama\images\map_icons\map_icon_ba_jail_electric_razor_go.svg failed to load.
Downloading https://fastdl.absynthium.com//serve.php?id=801669373897474486110977059&url=/materials/models/texture.vmt.bz2.
Error downloading https://fastdl.absynthium.com//serve.php?id=801669373897474486110977059&url=/materials/models/texture.vmt.bz2
Downloading https://fastdl.absynthium.com//serve.php?id=801669373897474486110977059&url=/materials/models/texture.vmt.
Download finished!
No pure server whitelist. sv_pure = 0
Error! Variable "$phongboost" is multiply defined in material "models/player/custom_player/econ/body/tm_jungle_raider/tm_jungle_raider_body_varianta"!
Error reading file resource/overviews/ba_jail_electric_razor_go_radar_spectate.dds.
MickaNoob s'est connecté.
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_INGAME
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--TERRORIST"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--CT"! Panel is possibly created dynamically.
Error reading file materials/panorama/images/map_icons/screenshots/1080p/ba_jail_electric_razor_go.png.
Error reading file materials/panorama/images/map_icons/screenshots/1080p/ba_jail_electric_razor_go.png.
Resource materials\panorama\images\map_icons\map_icon_ba_jail_electric_razor_go.svg failed to load.
window resized
```

After retry
```

Connected to 192.168.1.1:27015

Counter-Strike: Global Offensive
Map: ba_jail_electric_razor_go
Players: 1 (0 bots) / 2 humans
Build: 8853
Server Number: 3

WARNING: BSP loaded VertexLitGeneric material: KA_SOCCER_2006/BALLON2
WARNING: BSP loaded VertexLitGeneric material: CS_HAVANA/METALFLUORESCENTSIDES01
SignalXWriteOpportunity(3)
ConVarRef stripper_current_file doesn't point to an existing ConVar
SetConVar: No such cvar ( stripper_current_file set to ba_jail_electric_razor_go), skipping
Error reading file materials/panorama/images/map_icons/screenshots/1080p/ba_jail_electric_razor_go.png.
No pure server whitelist. sv_pure = 0
Error reading file resource/overviews/ba_jail_electric_razor_go_radar_spectate.dds.
MickaNoob s'est connecté.
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_INGAME
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--TERRORIST"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--CT"! Panel is possibly created dynamically.
Error reading file materials/panorama/images/map_icons/screenshots/1080p/ba_jail_electric_razor_go.png.
Error reading file materials/panorama/images/map_icons/screenshots/1080p/ba_jail_electric_razor_go.png.
Resource materials\panorama\images\map_icons\map_icon_ba_jail_electric_razor_go.svg failed to load.
```
I have already seen this message appear in previous versions

**Comment by Nolo001-Aha** [comment]
But the message does not appear now, right?

**Comment by MickaNoob** [comment]
Nop

**Comment by Nolo001-Aha** [comment]
Wild idea, but might work - can you check whether the game server has the fiingerprint file in it's files?

![image](https://user-images.githubusercontent.com/56518932/233801725-d6cf46e6-e494-40af-99a1-9080a0c30d71.png)

this path, to be precise. If it's there, delete the file on the server, delete the file locally and retry again.

**Comment by Nolo001-Aha** [comment]
If there's no such error in your console, then the Netmessage is constructed properly...

**Comment by MickaNoob** [comment]
When i delete rebanner.cfg 

I got materials/models/texture.vmt

**Comment by Nolo001-Aha** [comment]
Try to set a different fingerprint path in the config and re-load the plugin.
When choosing a custom fingerprint path, please consult the Wiki page, section 1 sub-section 4:
https://github.com/Nolo001-Aha/SourceMod-ReBanner/wiki/Setting-up-Re-Banner#1-first-launch-initialization

**Comment by MickaNoob** [comment]
Ok bro, it's working.
I changed the path. 
I found the error, the file that was pointed was existing on the server. 

```
Found existing fingerprint record (24726738219226135573724232) by SteamID match (STEAM_1:0:120031267). Sending through FastDownloads.
Diverting to new FastDownload address: https://fastdl.absynthium.com//serve.php?id=24726738219226135573724232&url=
Resetting to default FastDownload address.
L 04/22/2023 - 21:05:16: [weapons.smx] Inactive players' data has been deleted
PutClientInServer: no info_player_start on level
Tried to look up command NEXTMAP as if it were a variable.
Processing queued client MickaNoob, 1
Requesting client fingerpint via File Network...
Received fingerprint 24726738219226135573724232 of client MickaNoob. Processing...
```

![image](https://user-images.githubusercontent.com/20491694/233802176-3893ddb8-f978-4788-a86e-1d003cc187c7.png)


Great job ! 
Thanks for help :)

**Comment by Nolo001-Aha** [comment]
Thank god honestly, this was my last idea. Would it still not work, I'd start questioning my decisions...

Either way, I should also say THANK YOU - your reports helped me debug and make Re-Banner better!

If you have any issues, be sure to post them here.
Also keep an eye on the repo in general; the plugin is still in active development, and there could be more hidden bugs that I'm yet to discover and fix.
