### ISSUE TITLE
Stuck on "Requesting client fingerpint via File Network..."

### ISSUE THREAD

**Issue by PuNko6** [Nolo001-Aha/SourceMod-ReBanner#9]
Hi, I tried to setup your plugin, dowloading and everything works fine, but it doesn't do anything if i ban someone. There is no any data in database. My log looks like this:

[DEBUG] Generating new fingerprint for client PuNko
[DEBUG] Diverting to new FastDownload address: .....//serve.php?id=77559566994333519907000405&url=
[DEBUG] Resetting to default FastDownload address.
[DEBUG] Processing queued client PuNko
[DEBUG] Requesting client fingerpint via File Network...

**Comment by Nolo001-Aha** [comment]
Hello.

I assume you're on Linux CS:GO server.

The issue should be fixed - please download the latest versions of my fork of File Network and Re-Banner and compile them.

**Comment by Nolo001-Aha** [comment]
Fix confirmed in #7. Fixed code is in the main branches of Re-Banner and File Network, be sure to compile these.

Closing.
